version: 0.0
os: linux
files:
  - source: scripts/index.html
    destination: /usr/share/nginx/html/
hooks:
##  ApplicationStop:
##    - location: scripts/application_stop.sh
##      timeout: 60
##      runas: root
##  BeforeInstall:
##    - location: scripts/before_install.sh
##      timeout: 300
##      runas: root
  Install:
    - location: scripts/install_ngnix.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/copy_custom_index.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_ngnix.sh
      timeout: 300
      runas: root

