name: Deploy to AWS CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION

      - name: Create Deployment
        run: |
          cd awsactionsproject
          aws deploy create-deployment \
              --application-name myapplication \
              --deployment-group-name myapplicationDeploymentGroup \
              --deployment-config-name CodeDeployDefault.AllAtOnce \
              ##--github-location repository=your-repo-name,commitId=your-commit-id
              --github-location repository=${{ github.repository }},commitId=${{ github.sha }}


      - name: Wait for Deployment
        id: deployment
        run: |
          while true; do
            status=$(aws deploy get-deployment --query "deploymentInfo.status" --output text)
            if [ "$status" = "Succeeded" ]; then
              break
            elif [ "$status" = "Failed" ]; then
              exit 1
            fi
            sleep 30
          done

      - name: Deployment Status
        run: |
          echo "Deployment status: ${{ steps.deployment.outputs.status }}"



